name: CI

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        config:
          - name: Ubuntu
            os: ubuntu-latest
            cmake_preset: ci-linux
            build_dir: build/linux
            dist_dir: dist/linux
          - name: macOS
            os: macos-latest
            cmake_preset: ci-macos
            build_dir: build/linux
            dist_dir: dist/macos
          - name: Windows
            os: windows-latest
            cmake_preset: ci-windows
            build_dir: build/windows
            dist_dir: dist/windows
    
    steps:
      - name: Fetch submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Get godot-cpp current commit
        run: |
          cd godot-cpp
          echo "hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo $GITHUB_OUTPUT
        id: godot-cpp-hash
      
      - name: Get godot-cpp build cache
        uses: actions/cache@v3
        with:
          path: build/godot-cpp
          key: ${{ runner.os }}-${{ steps.godot-cpp-hash.hash }}

      - name: Build CoreGame
        id: configure
        run: |
          cmake --preset ${{ matrix.config.cmake_preset }}
          cmake --build ${{ matrix.config.build_dir }}
      
on:
  workflow_dispatch:
  push:
    paths:
      - src/**
      - .github/**
