name: CI
env:
  TARGET_NAME: CoreGame
  CPM_SOURCE_CACHE: ${{ github.workspace }}/.cache/CPM
  CCACHE_DIR: ${{ github.workspace }}/.cache/ccache
  ARTIFACT_LINUX: libCoreGame.so
  ARTIFACT_MACOS: libCoreGame.dylib
  ARTIFACT_WINDOWS: CoreGame.dll

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        config:
          - name: Ubuntu
            os: ubuntu-latest
            cmake_preset: ci-linux
            build_dir: build/linux
          - name: macOS
            os: macos-latest
            cmake_preset: ci-macos
            build_dir: build/macos
          - name: Windows
            os: windows-latest
            cmake_preset: ci-windows
            build_dir: build/windows

    steps:
      - name: Prerequisites
        id: deps
        run: |
          case $RUNNER_OS in
          Linux)
            sudo apt update && sudo apt install ccache
            cpus=$(nproc)
            artifact=${ARTIFACT_LINUX}
            ;;
          macOS)
            brew install ccache
            cpus=$(sysctl -n hw.ncpu)
            artifact=${ARTIFACT_MACOS}
            ;;
          Windows)
            choco install ccache
            cpus=${NUMBER_OF_PROCESSOR}
            artifact=${ARTIFACT_WINDOWS}
            ;;
          *)
            cpus=1
            ;;
          esac
          echo "Number of cores: ${cpus}"
          echo "cpus=${cpus}" >> $GITHUB_OUTPUT
          echo "artifact=${artifact}" >> $GITHUB_OUTPUT

      - name: Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.CPM_SOURCE_CACHE }}
            ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-${{ hashFiles('godot-cpp') }}

      - name: Cmake configure
        run: cmake --preset ${{ matrix.config.cmake_preset }}

      - name: Build godot-cpp
        run: cmake --build
          --preset ${{ matrix.config.cmake_preset }}
          -j ${{ steps.deps.outputs.cpus }}
          --target godot-cpp

      - name: Build CoreGame
        id: configure
        run: cmake --build
          --preset ${{ matrix.config.cmake_preset }}
          -j ${{ steps.deps.outputs.cpus }}
          --target ${{ env.TARGET_NAME }}
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.deps.outputs.artifact }}
          path: ${{ matrix.config.build_dir }}/${{ steps.deps.outputs.artifact }}

on:
  workflow_dispatch:
  push:
    paths:
      - src/**
      - .github/**
      - CMakeLists.txt
      - CMakePresets.json
      - extension_api.json
