name: CI
env:
  TARGET_NAME: CoreGame
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        config:
          - name: Ubuntu
            os: ubuntu-latest
            cmake_preset: ci-linux
            build_dir: build/linux
            dist_dir: dist/linux
          - name: macOS
            os: macos-latest
            cmake_preset: ci-macos
            build_dir: build/macos
            dist_dir: dist/macos
          - name: Windows
            os: windows-latest
            cmake_preset: ci-windows
            build_dir: build/windows
            dist_dir: dist/windows

    steps:
      - name: Fetch submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Get godot-cpp current commit
        id: godot-cpp-hash
        run: |
          cd godot-cpp
          echo "hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Cache godot-cpp
        id: godot-cpp-cache
        uses: actions/cache@v3
        with:
          path: ${{ matrix.config.build_dir }}/godot-cpp
          key: ${{ runner.os }}-${{ steps.godot-cpp-hash.outputs.hash }}

      - name: Build godot-cpp
        if: steps.godot-cpp-cache.outputs.cache-hit != 'true'
        run: |
          cmake --preset ${{ matrix.config.cmake_preset }}
          cmake --build --config Release --target godot-cpp

      - name: Build CoreGame
        id: configure
        run: |
          cmake --preset ${{ matrix.config.cmake_preset }}
          cmake --build --config Release --target ${{ env.TARGET_NAME }}

on:
  workflow_dispatch:
  push:
    paths:
      - src/**
      - .github/**
